-- MAISON Furniture Store - Database Schema
-- Run this in Supabase Cloud SQL Editor

-- Profiles table (auto-created on user signup)
CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  name text,
  email text,
  phone text,
  join_date text,
  is_admin boolean DEFAULT false
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON profiles FOR SELECT USING ( true );

CREATE POLICY "Users can insert their own profile."
  ON profiles FOR INSERT WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile."
  ON profiles FOR UPDATE USING ( auth.uid() = id );

-- Auto-create profile on signup
CREATE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, phone, join_date, is_admin)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.email),
    NEW.email,
    NEW.raw_user_meta_data->>'phone',
    to_char(NOW(), 'MM/DD/YYYY'),
    false
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Products table
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat text NOT NULL,
  name text NOT NULL,
  price numeric NOT NULL,
  old_price numeric,
  badge text,
  img text NOT NULL,
  imgs jsonb NOT NULL,
  category text NOT NULL,
  rating integer,
  reviews integer,
  "desc" text,
  material text,
  dimensions text,
  warranty text,
  delivery text,
  sku text,
  color text
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are viewable by everyone."
  ON products FOR SELECT USING ( true );

-- Orders table
CREATE TABLE public.orders (
  id text PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  date text,
  items jsonb NOT NULL,
  subtotal numeric NOT NULL,
  shipping numeric NOT NULL,
  total numeric NOT NULL,
  status text,
  customer jsonb
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own orders."
  ON orders FOR SELECT
  USING ( auth.uid() = user_id OR (SELECT is_admin FROM profiles WHERE id = auth.uid()) = true );

CREATE POLICY "Users can insert their own orders."
  ON orders FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

-- Seed product data
INSERT INTO public.products (id, cat, name, price, old_price, badge, img, imgs, category, rating, reviews, "desc", material, dimensions, warranty, delivery, sku, color)
VALUES
  (1, 'sofa', 'Oslo 3-Seat Sofa', 1299, 1799, 'New', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', '["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80","https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80","https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80"]', 'Sofas', 5, 128, 'The Oslo 3-Seat Sofa redefines comfort and sophistication.', 'Premium Italian Linen, Solid Walnut Legs', 'W:220cm × D:95cm × H:82cm', '5 Years', 'White-Glove, 7–14 days', 'MSN-SOFA-001', 'Linen Beige'),
  (2, 'table', 'Walnut Dining Table', 849, 1100, 'Hot', 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80', '["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80","https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=800&q=80"]', 'Tables', 5, 94, 'Crafted from solid American Black Walnut. Seats 6–8 comfortably.', 'Solid American Black Walnut', 'W:200cm × D:90cm × H:76cm', '5 Years', 'White-Glove, 10–21 days', 'MSN-TABLE-002', 'Walnut Dark'),
  (3, 'chair', 'Nordic Accent Chair', 389, 559, '-30%', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80', '["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80","https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80"]', 'Chairs', 4, 76, 'Inspired by mid-century Scandinavian design.', 'Beech Wood Frame, Wool Blend Upholstery', 'W:68cm × D:72cm × H:80cm', '3 Years', 'Standard, 5–10 days', 'MSN-CHAIR-003', 'Stone Grey'),
  (4, 'bed', 'Luxe King Bed Frame', 1599, null, null, 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80', '["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80","https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"]', 'Beds', 5, 211, 'Transform your bedroom into a luxury retreat.', 'European Oak, Velvet Upholstery, Brass Hardware', 'King: W:193cm × D:213cm × H:130cm', '5 Years', 'White-Glove, 14–21 days', 'MSN-BED-004', 'Midnight Velvet'),
  (5, 'sofa', 'Monaco L-Shape Sofa', 2199, 2799, 'New', 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80', '["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80","https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"]', 'Sofas', 5, 57, 'Our grandest sofa — an L-shaped sectional.', 'Top-Grain Leather, Kiln-Dried Hardwood Frame', 'W:310cm × D:210cm × H:85cm', '5 Years', 'White-Glove, 14–28 days', 'MSN-SOFA-005', 'Cognac Leather'),
  (6, 'table', 'Marble Coffee Table', 549, 699, null, 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=800&q=80', '["https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=800&q=80"]', 'Tables', 4, 43, 'Italian Carrara marble top on a blackened steel frame.', 'Carrara Marble Top, Blackened Steel Frame', 'W:110cm × D:65cm × H:42cm', '3 Years', 'Standard, 7–14 days', 'MSN-TABLE-006', 'White Marble'),
  (7, 'chair', 'Lounge Rocking Chair', 299, 399, '-25%', 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80', '["https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80"]', 'Chairs', 5, 89, 'Modern reinvention of the classic rocking chair.', 'Steambent Ash Wood, Hand-Woven Rattan', 'W:62cm × D:90cm × H:100cm', '3 Years', 'Standard, 5–10 days', 'MSN-CHAIR-007', 'Natural Ash'),
  (8, 'bed', 'Zen Platform Bed', 1199, 1499, 'Hot', 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80', '["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80","https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80"]', 'Beds', 5, 134, 'Low-profile Japanese-inspired platform bed in solid oak.', 'Solid White Oak, Natural Oil Finish', 'King: W:193cm × D:213cm × H:35cm', '5 Years', 'White-Glove, 10–21 days', 'MSN-BED-008', 'White Oak'),
  (9, 'sofa', 'Florence 2-Seat Sofa', 979, 1249, 'Sale', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80', '["https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80"]', 'Sofas', 4, 62, 'Italian elegance in a compact two-seater.', 'Bouclé Fabric, Solid Beech Frame, Brass Legs', 'W:165cm × D:88cm × H:78cm', '3 Years', 'Standard, 7–14 days', 'MSN-SOFA-009', 'Ivory Bouclé'),
  (10, 'table', 'Live Edge Oak Table', 1349, null, 'New', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', '["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"]', 'Tables', 5, 28, 'One-of-a-kind functional art.', 'Solid English Oak Slab, Steel Hairpin Legs', 'W:180–220cm × D:80–100cm × H:75cm', 'Lifetime', 'White-Glove, 21–35 days', 'MSN-TABLE-010', 'Raw Oak'),
  (11, 'chair', 'Executive Desk Chair', 469, 599, null, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80', '["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"]', 'Chairs', 4, 51, 'Ergonomic support with timeless aesthetics.', 'Full-Grain Leather, Polished Aluminium Base', 'W:66cm × D:70cm × H:105–115cm', '3 Years', 'Standard, 5–10 days', 'MSN-CHAIR-011', 'Chestnut Brown'),
  (12, 'bed', 'Cloud Storage Bed', 1899, 2299, 'Sale', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80', '["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80"]', 'Beds', 5, 93, 'Hydraulic lift storage system.', 'MDF Frame, Linen Upholstery, Hydraulic Lift', 'King: W:193cm × D:213cm × H:120cm', '10 Years', 'White-Glove, 14–21 days', 'MSN-BED-012', 'Warm Linen');

ALTER SEQUENCE public.products_id_seq RESTART WITH 13;
